services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=techmind_db
      - POSTGRES_USER=techmind_user
      - POSTGRES_PASSWORD=techmind_password

  datascience:
    build:
      context: ./Data Science/techmind-api
    ports:
      - "8000:8000"

  backend:
    build:
      context: ./backend/team19
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
      datascience:
        condition: service_healthy
    environment:
      - DB_USER=techmind_user
      - DB_PASSWORD=techmind_password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/techmind_db
      - MODEL_PYTHON_URL=http://datascience:8000/conteudo
      - MODEL_PYTHON_MOCK_ENABLED=false
      - CORS_ALLOWED_ORIGINS=http://localhost:3000

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
