spring.application.name=team19

# busca a variável da url pro Docker. Se não achar, usa o localhost como padrão
model.python.url=${MODEL_PYTHON_URL:https://techmind-api.onrender.com/conteudo}
# Api remota subida no Render: https://techmind-api.onrender.com/conteudo
# Api local: http://127.0.0.1:8000/conteudo

# busca a variável do Docker. Se não achar, usa false como padrão
model.python.mock-enabled=${MODEL_PYTHON_MOCK_ENABLED:false}

<<<<<<< HEAD
api.security.token.secret=${JWT_SECRET:my-secret-key}
=======
# comunicação entre back e front
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:*}
>>>>>>> feature/frontend

spring.datasource.url=jdbc:postgresql://localhost/techmind_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=true
